// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetailPosERP.API.Data;

#nullable disable

namespace RetailPosERP.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("RetailPosERP.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "8901234567890",
                            CreatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6569),
                            IsActive = true,
                            Name = "T-Shirt (M)",
                            Price = 499.00m,
                            ProductCode = "PRD-001",
                            StockQuantity = 80,
                            UpdatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6574)
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8901234567891",
                            CreatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6588),
                            IsActive = true,
                            Name = "Jeans (32)",
                            Price = 1299.00m,
                            ProductCode = "PRD-002",
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6588)
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "8901234567892",
                            CreatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6594),
                            IsActive = true,
                            Name = "Polo Shirt (L)",
                            Price = 799.00m,
                            ProductCode = "PRD-003",
                            StockQuantity = 70,
                            UpdatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6594)
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "8901234567893",
                            CreatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6599),
                            IsActive = true,
                            Name = "Jacket (XL)",
                            Price = 2499.00m,
                            ProductCode = "PRD-004",
                            StockQuantity = 20,
                            UpdatedAt = new DateTime(2026, 5, 10, 18, 55, 9, 661, DateTimeKind.Utc).AddTicks(6600)
                        });
                });

            modelBuilder.Entity("RetailPosERP.API.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UniqueSaleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UniqueSaleId")
                        .IsUnique();

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("RetailPosERP.API.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("RetailPosERP.API.Models.SaleItem", b =>
                {
                    b.HasOne("RetailPosERP.API.Models.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetailPosERP.API.Models.Sale", "Sale")
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("RetailPosERP.API.Models.Product", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("RetailPosERP.API.Models.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
